apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "default"
  namespace: "istio-system"
  annotations:
    configsync.gke.io/cluster-name-selector: exam
spec:
  mtls:
    mode: STRICT
